#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
  #- Указать настройки подключения к базе данных.
  #- Указать порт приложения.
  #- Настроить параметры безопасности и JWT.
  #- Включить Swagger UI.

spring:
  application:
    name: bankcards

  liquibase:
    change-log: classpath:/db/migration/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080